### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by apapadak** [dspinellis/greek-vat-data#7]
Hello,

The last few days, I'm sending a few (OPTIONS &) POST requests to the service since I'm trying a new AngularJS/jQuery client.
Have you disabled CORS/OPTIONS on the server, since the preflight OPTIONS requests return 404?

Through Postman (chrome plugin), I get results easily (it does a direct POST request), but through browsers, they have to do OPTIONS before POST and the OPTIONS request fails continuously.

-> XMLHttpRequest cannot load https://www1.gsis.gr/webtax2/wsgsis/RgWsPublic/RgWsPublicPort. Response for preflight has invalid HTTP status code 404

Thanks.

p.s. Haven't found time to test my code in the last days, I hope it's not a quirk I left in my last experiment runs. But it was running smoothly last Sunday. :)

**Comment by dspinellis** [comment]
There is not relationship between this project (or me) and the data providers.  I suggest you contact their technical support. Looking forward to receive your JS contribution!
